Console.Clear();
Console.WriteLine("Введите Х1: ");
double X1=Convert.ToDouble(Console.ReadLine());
Console.WriteLine("Введите Y1: ");
double Y1=Convert.ToDouble(Console.ReadLine());
Console.WriteLine("Введите Z1: ");
double Z1=Convert.ToDouble(Console.ReadLine());
Console.WriteLine("Введите Х2: ");
double X2=Convert.ToDouble(Console.ReadLine());
Console.WriteLine("Введите Y2: ");
double Y2=Convert.ToDouble(Console.ReadLine());
Console.WriteLine("Введите Z2: ");
double Z2=Convert.ToDouble(Console.ReadLine());
double length = Math.Sqrt((Math.Pow(X2-X1,2)+Math.Pow(Y2-Y1,2)+Math.Pow(Z2-Z1,2)));
Console.WriteLine(length);